# Generated by Django 5.2.6 on 2025-09-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.CharField(max_length=100)),
                ('telegram', models.CharField(max_length=100)),
                ('git', models.CharField(max_length=100)),
            ],
        ),
    ]
